TOPDIR = $(realpath ../..)

PROGRAM = floppy
SOURCES = main.c filesys.c
OBJECTS = ../startup.o ../fault.o ../trap.o 
LAUNCHOPTS = --window serial
ADF-EXTRA = adf-extra/*.txt

include $(TOPDIR)/build/build.prog.mk
