console.o: \
 /home/tomasz/Downloads/sju_terminal/terminal-ThomasStachovsky/examples/console/console.c \
 /home/tomasz/Downloads/sju_terminal/terminal-ThomasStachovsky/include/stdio.h \
 /home/tomasz/Downloads/sju_terminal/terminal-ThomasStachovsky/include/cdefs.h \
 /home/tomasz/Downloads/sju_terminal/terminal-ThomasStachovsky/include/stdint.h \
 /home/tomasz/Downloads/sju_terminal/terminal-ThomasStachovsky/include/file.h \
 /home/tomasz/Downloads/sju_terminal/terminal-ThomasStachovsky/include/bitmap.h \
 /home/tomasz/Downloads/sju_terminal/terminal-ThomasStachovsky/include/copper.h \
 /home/tomasz/Downloads/sju_terminal/terminal-ThomasStachovsky/include/custom.h \
 /home/tomasz/Downloads/sju_terminal/terminal-ThomasStachovsky/include/custom_regdef.h \
 /home/tomasz/Downloads/sju_terminal/terminal-ThomasStachovsky/include/font.h \
 /home/tomasz/Downloads/sju_terminal/terminal-ThomasStachovsky/examples/console/console.h
