event.o: \
 /home/tomasz/Downloads/sju_terminal/terminal-ThomasStachovsky/examples/console/event.c \
 /home/tomasz/Downloads/sju_terminal/terminal-ThomasStachovsky/include/FreeRTOS/FreeRTOS.h \
 /home/tomasz/Downloads/sju_terminal/terminal-ThomasStachovsky/include/stdint.h \
 /home/tomasz/Downloads/sju_terminal/terminal-ThomasStachovsky/FreeRTOSConfig.h \
 /home/tomasz/Downloads/sju_terminal/terminal-ThomasStachovsky/include/FreeRTOS/projdefs.h \
 /home/tomasz/Downloads/sju_terminal/terminal-ThomasStachovsky/include/FreeRTOS/portable.h \
 /home/tomasz/Downloads/sju_terminal/terminal-ThomasStachovsky/include/FreeRTOS/deprecated_definitions.h \
 /home/tomasz/Downloads/sju_terminal/terminal-ThomasStachovsky/FreeRTOS/portable/m68k-amiga/portmacro.h \
 /home/tomasz/Downloads/sju_terminal/terminal-ThomasStachovsky/include/cdefs.h \
 /home/tomasz/Downloads/sju_terminal/terminal-ThomasStachovsky/include/FreeRTOS/mpu_wrappers.h \
 /home/tomasz/Downloads/sju_terminal/terminal-ThomasStachovsky/include/FreeRTOS/queue.h \
 /home/tomasz/Downloads/sju_terminal/terminal-ThomasStachovsky/include/FreeRTOS/task.h \
 /home/tomasz/Downloads/sju_terminal/terminal-ThomasStachovsky/include/FreeRTOS/list.h \
 /home/tomasz/Downloads/sju_terminal/terminal-ThomasStachovsky/examples/console/event.h \
 /home/tomasz/Downloads/sju_terminal/terminal-ThomasStachovsky/include/mouse.h \
 /home/tomasz/Downloads/sju_terminal/terminal-ThomasStachovsky/include/keyboard.h \
 /home/tomasz/Downloads/sju_terminal/terminal-ThomasStachovsky/include/FreeRTOS/task.h
