main.o: /home/tomasz/FreeRTOS-Amiga/examples/instemul/main.c \
 /home/tomasz/FreeRTOS-Amiga/include/FreeRTOS/FreeRTOS.h \
 /home/tomasz/FreeRTOS-Amiga/include/stdint.h \
 /home/tomasz/FreeRTOS-Amiga/FreeRTOSConfig.h \
 /home/tomasz/FreeRTOS-Amiga/include/FreeRTOS/projdefs.h \
 /home/tomasz/FreeRTOS-Amiga/include/FreeRTOS/portable.h \
 /home/tomasz/FreeRTOS-Amiga/include/FreeRTOS/deprecated_definitions.h \
 /home/tomasz/FreeRTOS-Amiga/FreeRTOS/portable/m68k-amiga/portmacro.h \
 /home/tomasz/FreeRTOS-Amiga/include/cdefs.h \
 /home/tomasz/FreeRTOS-Amiga/include/FreeRTOS/mpu_wrappers.h \
 /home/tomasz/FreeRTOS-Amiga/include/FreeRTOS/task.h \
 /home/tomasz/FreeRTOS-Amiga/include/FreeRTOS/list.h \
 /home/tomasz/FreeRTOS-Amiga/include/custom.h \
 /home/tomasz/FreeRTOS-Amiga/include/custom_regdef.h \
 /home/tomasz/FreeRTOS-Amiga/include/trap.h
